spring:
  datasource:
    url: jdbc:hsqldb:file:db/addressdb
  jpa:
    hibernate:
      ddl-auto: update

dev-profile:
  value: false
  
postcoder:
  search_key: PCW3Y-V28MF-PHNS7-FWCVH
  method: address
  search_term: ?format=json 